# Generated by Django 4.2.29 on 2026-04-03 09:05

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount (must be positive)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], db_index=True, max_length=10)),
                ('category', models.CharField(db_index=True, help_text='e.g., food, salary, rent, travel', max_length=100)),
                ('date', models.DateField(db_index=True, help_text='Date of the transaction')),
                ('notes', models.TextField(blank=True, default='', help_text='Optional additional description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial Record',
                'verbose_name_plural': 'Financial Records',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='transaction_user_id_1cb814_idx'), models.Index(fields=['user', 'type'], name='transaction_user_id_79e2cc_idx'), models.Index(fields=['user', 'category'], name='transaction_user_id_fb59f9_idx')],
            },
        ),
    ]
